### ISSUE TITLE
cc not found on Mac OSX Montery

### ISSUE THREAD

**Issue by thejeff77** [passepartoutvpn/openssl-apple#48]
Seems like a lot of these guys can't find cc or something. Anyone had this issue before?

/usr/bin/cc: No such file or directory
make[1]: *** [crypto/aes/aes_cbc.o] Error 127
/bin/sh: /Library/Developer/CommandLineTools/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc: No such file or directory
make[1]: *** [crypto/aes/aes_cfb.o] Error 127
/bin/sh: /Library/Developer/CommandLineTools/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc: No such file or directory
make[1]: *** [crypto/aes/aes_core.o] Error 127
/bin/sh: /Library/Developer/CommandLineTools/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc: No such file or directory
make[1]: *** [crypto/aes/aes_ecb.o] Error 127
make: *** [all] Error 2

**Comment by keeshux** [comment]
Absolutely unrelated.
