### ISSUE TITLE
Building for Catalyst13.0-x86_64.sdk occur error

### ISSUE THREAD

**Issue by IceSilkworm** [passepartoutvpn/openssl-apple#49]
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc  -I. -Iinclude -fPIC -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.0.sdk -fno-common -fembed-bitcode -target x86_64-apple-ios13.0-macabi -mios-version-min=13.0 -O3 -Wall -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/Users/ring/Library/Caches/CocoaPods/Pods/Release/OpenSSL-Apple/1.1.1l.11-fb93d/bin/Catalyst13.0-x86_64.sdk/ssl\"" -DENGINESDIR="\"/Users/ring/Library/Caches/CocoaPods/Pods/Release/OpenSSL-Apple/1.1.1l.11-fb93d/bin/Catalyst13.0-x86_64.sdk/lib/engines-1.1\"" -D_REENTRANT -DNDEBUG -DOPENSSL_API_COMPAT=0x10100000L  -MMD -MF crypto/aes/aes_ecb.d.tmp -MT crypto/aes/aes_ecb.o -c -o crypto/aes/aes_ecb.o crypto/aes/aes_ecb.c
clangclang: : error: clangclang: error: : invalid version number in '-target x86_64-apple-ios13.0-macabi'
invalid version number in '-target x86_64-apple-ios13.0-macabi'
error: invalid version number in '-target x86_64-apple-ios13.0-macabi'
error: invalid version number in '-target x86_64-apple-ios13.0-macabi'
clang: error: invalid version number in '-target x86_64-apple-ios13.0-macabi'
clang: error: invalid version number in '-target x86_64-apple-ios13.0-macabi'
clang: error: invalid version number in '-target x86_64-apple-ios13.0-macabi'
make[1]: *** [apps/app_rand.o] Error 1
make[1]: *** Waiting for unfinished jobs....
clang: error: invalid version number in '-target x86_64-apple-ios13.0-macabi'
make[1]: *** [crypto/aes/aes_cfb.o] Error 1
make[1]: *** [apps/s_socket.o] Error 1
make[1]: *** [crypto/aes/aes_ecb.o] Error 1
make[1]: *** [crypto/aes/aes_core.o] Error 1
make[1]: *** [apps/s_cb.o] Error 1
make[1]: *** [crypto/aes/aes_cbc.o] Error 1
make[1]: *** [apps/bf_prefix.o] Error 1
clang: error: invalid version number in '-target x86_64-apple-ios13.0-macabi'
clang: error: invalid version number in '-target x86_64-apple-ios13.0-macabi'
make[1]: *** [apps/apps.o] Error 1
make[1]: *** [apps/opt.o] Error 1
make: *** [all] Error 2

**Comment by IceSilkworm** [comment]
The problem occurs in the latest Xcode of the latest Mac system！

**Comment by keeshux** [comment]
Latest script has 14.0-macabi, are you up to date?
