### ISSUE TITLE
Help - invalid x86_64

### ISSUE THREAD

**Issue by thejeff77** [passepartoutvpn/openssl-apple#50]
pple/bin/iPhoneSimulator16.2-x86_64.sdk/build-openssl-1.1.1q.log
		 apps/libapps.a -lssl -lcrypto  
Undefined symbols for architecture x86_64:
  "_opendir$INODE64", referenced from:
      _OPENSSL_DIR_read in libcrypto.a(o_dir.o)
  "_readdir$INODE64", referenced from:
      _OPENSSL_DIR_read in libcrypto.a(o_dir.o)
ld: symbol(s) not found for architecture x86_64

Input command: `./build-libssl.sh --version=1.1.1d --archs="ios_armv7 ios_arm64 ios_i386 ios_arm64e" --targets="ios-sim-cross-x86_64 ios64-cross-arm64 ios64-cross-arm64e"`

Any help would be appreciated. What are all the supported targets?

**Comment by keeshux** [comment]
I understand you fail to compile on Intel Mac, correct?

**Comment by thejeff77** [comment]
Yes, this is an Intel Mac. Thanks for the quick response.

**Comment by keeshux** [comment]
Too bad I have no way to test this. I have an M1.

**Comment by thejeff77** [comment]
Does this command work on the M1?

I don't know how or if the type of processor impacts the running of this compile command.
