### ISSUE TITLE
Workflow fails due to missing xrOS platform

### ISSUE THREAD

**Issue by keeshux** [passepartoutvpn/openssl-apple#61]
Action silently fails because Xcode 15.2 is required in CI. Notice the missing xrOS version, actually the script should look up platform existence in advance:

https://github.com/passepartoutvpn/openssl-apple/actions/runs/7485638720

Waiting on https://github.com/actions/runner-images/issues/9139

If it takes longer than expected, exclude xrOS targets from workflow for now.

**Comment by nicop2000** [comment]
any update on this?
