### ISSUE TITLE
AppStore Rejection due to openssl dependency ‼️🚨

### ISSUE THREAD

**Issue by arturdev** [passepartoutvpn/openssl-apple#63]
In my project, only two packages has a dependency to openssl. Firebase and TunnelKit. 

More context here: 
https://github.com/firebase/firebase-ios-sdk/issues/12888

**Comment by 0xBF90E913** [comment]
Hey dude. Did you manage to somehow fix this?

**Comment by arturdev** [comment]
Yes... 
Had to use another library

**Comment by NasrullahKhan** [comment]
@keeshux 

i'm trying to create the vpn app.. as soon as i try to add testflight build into external group app status change to "invalid binary" and i recieve below email.. Please help

Please correct the following issues and upload a new binary to App Store Connect.

ITMS-91065: Missing signature - Your app includes “Frameworks/openssl.framework/openssl”, which includes BoringSSL / openssl_grpc, an SDK that was identified in the documentation as a privacy-impacting third-party SDK. If a new app includes a privacy-impacting SDK, or an app update adds a new privacy-impacting SDK, the SDK must include a signature file. Please contact the provider of the SDK that includes this file to get an updated SDK version with a signature. For details about verifying the code signature for a third-party SDK, visit: https://developer.apple.com/documentation/xcode/verifying-the-origin-of-your-xcframeworks.

**Comment by 0xBF90E913** [comment]
@keeshux brother, u can fix that?

**Comment by 0xBF90E913** [comment]
@keeshux As far as I understand, to fix it you need to sign some binary files in your project

**Comment by keeshux** [comment]
I wonder how people could feel so entitled to demand stufff with such urgency for software they didn’t pay a single cent for. I read no single line of courtesy for the work I shared.

The guy commenting above you has leeched and infringed the license of my libraries for years and has the guts to spam GitHub and send me e-mails for free support.

Sorry but this lack of appreciation drives me literally nuts.

I’ll fix this when I’ll be able to, but certainly I owe you guys nothing. Much rather the opposite, yet I fail to see any sincere “thank you” well before asking anything.

Feel free to look for alternatives.

**Comment by keeshux** [comment]
Moreover, you can just sign it yourself. No big deal.

Setting up code signing for a repo with CI/CD, on the other hand, is very time-consuming.

**Comment by 0xBF90E913** [comment]
> Moreover, you can just sign it yourself. No big deal.
> 
> Setting up code signing for a repo with CI/CD, on the other hand, is very time-consuming.

Tell me how to do this? Perhaps you can point me to the right article on Google? I haven't had to do this before

**Comment by zeeqmir** [comment]
@keeshux I'm new to development and your repo helped me a lot to write my first app, thanks for that. Whenever I submit the app to apple store it declines with message "ITMS-91065: Missing signature - Your app includes Frameworks/openssl.framework/openssl”,"

Could you please guide me (noob guide) how to get this fixed?

**Comment by keeshux** [comment]
FYI this is likely a developer issue with code-signing. Thanks for reporting but I'm closing this as non-issue.
