### ISSUE TITLE
openSSL changed url endpoints

### ISSUE THREAD

**Issue by ErikEverson** [passepartoutvpn/openssl-apple#67]
The URL used to download openSSL is no longer working 
"Downloading openssl-3.2.0.tar.gz...
An error occurred trying to find OpenSSL 3.2.0 on https://www.openssl.org/source/old/3.2.0/openssl-3.2.0.tar.gz
Please verify that the version you are trying to build exists, check cURL's error message and/or your network connection."

The new url is https://openssl.org/source/old/3.2/openssl-3.2.0.tar.gz

An issue has been filed in the openSSL repo to see if they didn't intend for these old url's to be dropped.

openSSL issue: https://github.com/openssl/web/issues/490 

If OpenSSL resolves this on their end there may be nothing to do on here to fix it

**Comment by keeshux** [comment]
It works for me, maybe they fixed it in the meantime? Thanks for reporting anyway.
