### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by phatblat** [passepartoutvpn/openssl-apple#71]
I'm looking to have a release (and tag) of this repo that contains #68. What's the process of creating a release? Are you waiting for anything before creating a release?

**Comment by keeshux** [comment]
@phatblat good reminder, let's see how it goes → https://github.com/passepartoutvpn/openssl-apple/actions/runs/11360540580

**Comment by phatblat** [comment]
Thanks, @keeshux! I see [3.2.0 (8)](https://github.com/passepartoutvpn/openssl-apple/releases/tag/3.2.108) is live now.
